[BLKTAP] Fix hotplug script to check if specified file exists.
Now users will see the following error:

[root@bebop ~]# xm create -c 128
Using config file "/etc/xen/128".
Error: Device 51713 (tap) could not be connected.
/tmp/128.img does not exist

Signed-off-by: Ryan Harper <ryanh@us.ibm.com>